# URL
baseURL: "https://frrouting.org/"

# Git versioning
enableGitInfo: true

# HTML files output to www/
publishDir: "www"

# Make permalinks to releases look pretty
permalinks:
  releases: /:year/:month/:filename/

# Append to <title> in most spots
title: "FRRouting"

# <html lang="...">
languageCode: "en-US"

params:
  # Off-site links, aggregated here in case they need to be changed later
  extLinks:
    github: "https://github.com/FRRouting/frr"
    frrwww: "https://github.com/FRRouting/frr-www"
    ci: "https://ci1.netdef.org/browse/FRR"
    mailList: "https://lists.frrouting.org"
    userDoc: "https://docs.frrouting.org/en/latest/"
    devDoc: "https://docs.frrouting.org/projects/dev-guide/en/latest/"
    slackJoinLink: "https://join.slack.com/t/frrouting/shared_invite/zt-2i48i105w-rNIIDKg7oX1YHwbRWgzi7A"
  # Intrasite links, these are used during template render for <header> hrefs
  # and other links
  localLinks:
    home: "/"
    releases: "/release"
    community: "/community"
    css: "/css"
    img: "/img"
    doc: "/doc"
