#! /bin/bash -e
#-------------------------------------------------------------------------------
#
# Copyright 2017 Cumulus Networks, inc all rights reserved
# author: jrrivers@cumulusnetworks.com
# license: GPL-2
#
# Pulls the FRR user guide from a source/build tree into the web site tree and
# applies the web site styles
#
#-------------------------------------------------------------------------------

usage() {
    [ "$*" == "" ] || echo; echo "$*"
    echo
    echo "$0 pulls the FRR user guide from a source/build tree into the web site tree and"
    echo "applies the web site styles."
    echo
    echo "usage: $0 <path-to-frr-build-tree>"
    echo "       <path-to-frr-build-tree> points to a project source tree in which the docs have"
    echo "       been build using \"make html\"."
    echo
    exit 1
}

#-------------------------------------------------------------------------------

DEV_SRC_DIR=$1/doc/developer/_build/html
USR_SRC_DIR=$1/doc/user/_build/html

# Sanity check the source directory
#
[ $# == 1 ] ||
    usage "Expecting a pointer to a build tree"
[ -d $1/zebra ] ||
    usage "\"$1\" does not look like an frr source/build directory"
if [ ! -d $USR_SRC_DIR ] || [ ! -f $USR_SRC_DIR/index.html ]; then
    usage "Does not look like you've built frr user docs in \"$1/doc/\".  Try \"make FRR.html\""
fi
if [ ! -d $DEV_SRC_DIR ] || [ ! -f $DEV_SRC_DIR/index.html ]; then
    usage "Does not look like you've built frr dev docs in \"$1/doc/\".  Try \"make developer.html\""
fi

# Prep the destination directory
USR_DST_DIR=./www/user-guide
DEV_DST_DIR=./www/dev-guide
rm -rf $(pwd)/$USR_DST_DIR/*
rm -rf $(pwd)/$DEV_DST_DIR/*

#-------------------------------------------------------------------------------
#
# Pull in the manual
#

for I in $DEV_SRC_DIR/*
do
    F=$DEV_DST_DIR/$(basename $I)
    case $F in
	*.html)  echo "styling ... $F"
		 # This section may be used for style transformations if
		 # needed, but it is preferred to do this using Sphinx's
		 # builtin theme customization facilities

		 #touch $F
		 #cat templates/header.html >> $F
		 #sed -e '/^<\/style>$/ r css-links' $I >> $F
		 #cat templates/footer.html >> $F
		 ;&
	*)       echo "copying ... $F"
		 cp -r $I $F
		 ;;
    esac
done

for I in $USR_SRC_DIR/*
do
    F=$USR_DST_DIR/$(basename $I)
    case $F in
	*.html)  echo "styling ... $F"
		 # This section may be used for style transformations if
		 # needed, but it is preferred to do this using Sphinx's
		 # builtin theme customization facilities

		 #touch $F
		 #cat templates/header.html >> $F
		 #sed -e '/^<\/style>$/ r css-links' $I >> $F
		 #cat templates/footer.html >> $F
		 ;&
	*)       echo "copying ... $F"
		 cp -r $I $F
		 ;;
    esac
done

exit 0
